version: '3'
services:
  web:
    image: cjaikaeo/elab-base
    container_name: elab-web
    depends_on:
      - db
    tty: true
    environment:
      TZ: "Asia/Bangkok"
      DJANGO_ADMIN_USER: "admin"
      DJANGO_ADMIN_PASSWORD: "adminpw"
    volumes:
      - ./src/elabsheet:/home/elab/app/elabsheet
      - ./scripts:/scripts
    # restart: always
    entrypoint: "/scripts/start-web.sh"

  grader:
    image: cjaikaeo/elab-base
    container_name: elab-grader
    depends_on:
      - web
    tty: true
    environment:
      TZ: "Asia/Bangkok"
    volumes:
      - ./src/elabsheet:/home/elab/app/elabsheet
      - ./scripts:/scripts
    # restart: always
    entrypoint: "/scripts/start-grader.sh"

  db:
    image: mysql:5.7
    container_name: elab-db
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_USER: "elab"
      MYSQL_PASSWORD: "elabdbpass"
      MYSQL_DATABASE: "elab"
      MYSQL_ROOT_PASSWORD: "mysql20181008"
    # volumes:
    #   # - ./db/etc/custom.cnf:/etc/mysql/conf.d/custom.cnf
    #   - ./db/mysql-datadir:/var/lib/mysql
    # restart: always

  nginx:
    image: nginx:1.15.5
    container_name: elab-nginx
    depends_on:
      - web
    environment:
      TZ: "Asia/Bangkok"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./src/elabsheet/public/media:/media
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:8000
    # restart: always

  nginx-proxy:
    image: nginx:1.15.5
    container_name: elab-nginx-proxy
    depends_on:
      - nginx
    environment:
      TZ: "Asia/Bangkok"
    volumes:
      - ./nginx/conf-proxy.d:/etc/nginx/conf.d
    ports:
      - 9000:9000
    # restart: always
